name: OSV Scanner

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: latest

      - name: Install OSV Scanner
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@latest

      - name: Scan for Vulnerabilities
        run: osv-scanner -r ../../.

      - name: Report Vulnerabilities
        run: osv-scanner report